---
name: Deploy to Firebase Hosting on PR
on: pull_request
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_DEMO_B66D6 }}
          projectId: angular-demo-b66d6
        run:
          touch .env
          echo FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }} >> .env
          echo FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }} >> .env
          echo FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }} >> .env
          cat .env
